# Generated by Django 4.2.1 on 2023-06-01 12:05

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='название')),
                ('active', models.BooleanField(default=False, verbose_name='активная')),
                ('favourite', models.BooleanField(default=False, verbose_name='избранная категория')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='products.category', verbose_name='родитель')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='цена')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('fullDescription', models.TextField(default='', verbose_name='полное описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('limited_edition', models.BooleanField(default=False, verbose_name='ограниченная серия')),
                ('freeDelivery', models.BooleanField(default=False, verbose_name='бесплатная доставка')),
                ('rating', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False, verbose_name='активный')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='название')),
                ('category', models.ManyToManyField(related_name='specifications', to='products.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePrice', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='цена по скидке')),
                ('dateFrom', models.DateField(default='', verbose_name='старт продаж')),
                ('dateTo', models.DateField(blank=True, null=True, verbose_name='окончание продаж')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'распродажа',
                'verbose_name_plural': 'распродажи',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128, verbose_name='автор')),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(verbose_name='текст')),
                ('rate', models.PositiveSmallIntegerField(default=5, verbose_name='оценка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=256, verbose_name='значение')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specification_name', to='products.specification', verbose_name='название')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specifications', to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'характеристика продукта',
                'verbose_name_plural': 'характеристики продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=products.models.product_image_directory_path, verbose_name='изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'изображение продукта',
                'verbose_name_plural': 'изображения продуктов',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CategoryIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(max_length=500, upload_to=products.models.category_image_directory_path, verbose_name='иконка')),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'иконка категории',
                'verbose_name_plural': 'иконки категорий',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=128, verbose_name='имя')),
                ('product', models.ManyToManyField(related_name='tags', to='products.product', verbose_name='тэг')),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'тэги',
                'indexes': [models.Index(fields=['name'], name='name_ind')],
            },
        ),
    ]
