# Generated by Django 4.1.7 on 2023-06-09 20:47

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image_alter_categoryicons_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(null=True, upload_to=products.models.product_image_directory_path, verbose_name='изображение'),
        ),
    ]
